name: （実作業）機能追加
description: 機能追加はこちら
labels: 実作業
title: '機能追加: '
body:
  - type: textarea
    id: purpose
    attributes:
      label: 目的
      description: この業務の目的を記載してください。
    validations:
      required: true
  - type: textarea
    id: method
    attributes:
      label: 方法
      description: どのような方法で業務を進めていくか記載してください。
    validations:
      required: true
  - type: textarea
    id: complete
    attributes:
      label: 終了要件
      description: このissueをcloseする条件を記載してください。
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 補足